language: java

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

before_script:
  - chmod +x gradlew
script:
  - ./gradlew check
after_success:
  - bash <(curl -s https://codecov.io/bash)

